// 'use client';

import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';
import '../utils/_typography.scss';
import Header from '@/components/Header/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-inter',
  preload: true,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body className={`bg-white antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
